[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
astar = "${ASTAR_RPC_URL}"
localhost = "${LOCALHOST}"