[profile.default]
src = "src"
out = "out"
libs = ["lib"]

unchecked_cheatcode_artifacts = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
astar = "${ASTAR_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
localhost = "${LOCALHOST}"